name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Descargar últimos cambios y levantar Docker
        run: |
          echo "--- Ejecutando despliegue local interno ---"
          cd /var/www/flask-prestamos
          git reset --hard HEAD
          git pull origin main
          docker compose up -d --build
          echo "--- ¡Despliegue completado con éxito! ---"
